import { Inter } from "next/font/google";
import "./globals.css";
import UserContextProvider from "@/context/UserContextProvider";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <NextTopLoader height={5} />
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
